describe('test', () => {
    beforeEach('go to site', () => {
        cy.request('https://www.saucedemo.com')
            .should((response) => {
                expect(response.status).to.eq(200)
            })
        cy.visit("https://www.saucedemo.com")
        cy.get('[data-test="username"]').type("standard_user")
        cy.get('[data-test="password"]').type("secret_sauce")
        cy.get('[data-test="login-button"]').click()
    })
    it('login error', () => {
        cy.get('#react-burger-menu-btn').click()
        cy.get('[data-test="logout-sidebar-link"]').click()
        cy.get('[data-test="username"]').type("locked_out_user")
        cy.get('[data-test="password"]').type("secret_sauce")
        cy.get('[data-test="login-button"]').click()
        cy.get('[data-test="error"]').should('exist')
    })
    it('add to cart', () => {
        cy.get('.product_sort_container')
            .select('hilo')
        cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').click()
        cy.get('[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]').click()
        cy.get('[data-test="add-to-cart-sauce-labs-fleece-jacket"]').click()
        cy.get('[data-test="add-to-cart-sauce-labs-bike-light"]').click()
        cy.get('[data-test="remove-sauce-labs-backpack"]').click()
    })
    it('order', () => {
        cy.get('.product_sort_container')
            .select('hilo')
        cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').click()
        cy.get('[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]').click()
        cy.get('[data-test="add-to-cart-sauce-labs-fleece-jacket"]').click()
        cy.get('[data-test="add-to-cart-sauce-labs-bike-light"]').click()
        cy.get('[data-test="remove-sauce-labs-backpack"]').click()
        cy.get('[data-test="shopping-cart-link"]').click()
        cy.get('[data-test="remove-sauce-labs-bike-light"]').click()
        cy.get('[data-test="continue-shopping"]').click()
        cy.get('[data-test="add-to-cart-sauce-labs-onesie"]').click()
        cy.get('[data-test="shopping-cart-link"]').click()
        cy.get('[data-test="checkout"]').click()
        cy.get('[data-test="firstName"]').type("name")
        cy.get('[data-test="lastName"]').type("surname")
        cy.get('[data-test="postalCode"]').type("1000")
        cy.get('[data-test="continue"]').click()
        let sum = 0;
        cy.get('[data-test="inventory-item-price"]').each(($el) => {
            sum += +$el.text().replace('$', '')
        }).then(() => {
            cy.get('[data-test="subtotal-label"]').then(($subtotal) => {
                const total = +$subtotal.text().replace('Item total: $', '')
                expect(sum).to.eq(total)
            })
        })
        cy.get('[data-test="finish"]').click()
        cy.get('[data-test="complete-header"]').should('be.visible')
    })
})